# ----------------------------------------------------------
# Configuration
# ----------------------------------------------------------
  baseURL = 'https://www.example.com/'
  languageCode = 'en'
  title = 'Site name'
  copyright = '2023 Copyright information'
  publishDir = 'public'
  enableInlineShortcodes = true
  disableHugoGeneratorInject = true
  disableKinds = ['rss', 'sitemap']

# ----------------------------------------------------------
# Parameters
# - rss_feed requires 'rss' removed from disableKinds above. 
# - js_theme requires theme-switch enabled in tocss.scss.
# ----------------------------------------------------------
  [params]
  
  description = 'Description metadata for search results best capped at 160 characters for good output.'
  author = 'Site author'
  email = "mailto:site-author@example.com"
  twitter = "https://twitter.com/example-com"
  mastodon = "https://mastodon.social/@example-com"
  github = "https://github.com/example-com"
  banner = "/img/banner.png"
  social_meta = 'false'
  rss_feed = 'false'  
  js_theme = 'true'
  js_menu = 'false'
  js_dialog = 'true'
  js_accordion = 'false'
  css_standard = 'true'
  css_minify = 'false'
  css_inline = 'false'

# ----------------------------------------------------------
# Menus
# ----------------------------------------------------------  
  [[menu.main]]
    identifier = 'home'
    name = 'home'
    url = '/'
    weight = -1

# ----------------------------------------------------------
# Taxonomy
# - disables default categories configuration
# ----------------------------------------------------------
  [taxonomies]
    tags = 'tags'

# ----------------------------------------------------------
# Markup
# - typographer disables curly quotes in summaries.
# - unsafe allows writing HTML in MD documents.
# - autoHeadingID disables TOC auto-IDs for MD headings.
# - noClasses allows custom Chroma syntax highlighting.
# ----------------------------------------------------------
  [markup]
  
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false  
                   
    [markup.goldmark.renderer]
      unsafe = true        
      
    [markup.goldmark.parser]
      autoHeadingID = false
      
    [markup.highlight]
      noClasses = false

# ----------------------------------------------------------
# Minify HTML
# ----------------------------------------------------------
  [minify]
    minifyOutput = false

# ----------------------------------------------------------
# Module mounts
# ----------------------------------------------------------
  [module]
  
  [[module.mounts]]
    source = 'static'
    target = 'static'  
    
  [[module.mounts]]
    source = 'assets/img'
    target = 'static/img'